remove lshell
There is security related issue with lshell, and it is not
maintained now. So remove it from our system to avoid
security issue.

To remove lshell:
1. Package sudo-config is created for wrs.sudo configure file
following the refactor process.
2. ldapusersetup in ldapscripts is modified to use bash only.
lshell support is removed.

ldapusersetup related patches are merged into 1 for easy
maintenance.

Test has been done:
Build and deploy test is done, also unit tests for ldap are
executed with pass, except lshell related test.

Closes-Bug: 1795451

Change-Id: Ia5de1bc94d22eb6c9bea6d9a96e92564ad848b19
Signed-off-by: slin14 <shuicheng.lin@intel.com>

diff --git a/ldap/ldapscripts/files/ldap-user-setup-support.patch b/ldap/ldapscripts/files/ldap-user-setup-support.patch
--- a/ldap/ldapscripts/files/ldap-user-setup-support.patch
+++ b/ldap/ldapscripts/files/ldap-user-setup-support.patch
@@ -1,12 +1,17 @@
 ---
- Makefile                 |    5 
- man/man1/ldapusersetup.1 |   61 ++++++++++
- sbin/ldapusersetup       |  263 +++++++++++++++++++++++++++++++++++++++++++++++
- 3 files changed, 327 insertions(+), 2 deletions(-)
+ Makefile                 |   5 +-
+ man/man1/ldapusersetup.1 |  60 +++++++++++
+ sbin/ldapusersetup       | 254 +++++++++++++++++++++++++++++++++++++++++++++++
+ 3 files changed, 317 insertions(+), 2 deletions(-)
+ create mode 100644 man/man1/ldapusersetup.1
+ create mode 100644 sbin/ldapusersetup
 
+diff --git a/sbin/ldapusersetup b/sbin/ldapusersetup
+new file mode 100644
+index 0000000..27d12dc
 --- /dev/null
 +++ b/sbin/ldapusersetup
-@@ -0,0 +1,263 @@
+@@ -0,0 +1,254 @@
 +#!/bin/sh
 +
 +#  ldapusersetup : interactive setup for adding users to LDAP
@@ -33,7 +38,6 @@
 +  echo "Usage : $0 [-u <username | uid> <field> <value>]
 +where accepted field(s) are as follows:
 +--sudo                        : whether to add this user to sudoer list
-+--shell <\"bash\"|\"lshell\"> : choose the shell for this user (default is lshell)
 +--secondgroup <grp>           : the secondary group to add this user to
 +--passmax     <value>         : the shadowMax value for this user
 +--passwarning <value>         : the shadowWarning value for this user"
@@ -46,12 +50,35 @@
 +
 +# runtime defaults
 +_DEFAULTGRP2="wrs_protected"
-+_DEFAULTLSHELL="/usr/local/bin/cgcs_cli"
++_BASHSHELL="/bin/bash"
 +_DEFAULTSHADOWMAX="90"
 +_DEFAULTSHADOWWARNING="2"
 +_SHELL=""
 +
 +### Helper functions ###
++
++# Gets input from user and validates it.
++# Will only return if input meets validation
++# criteria otherwise will just sit there.
++#
++# Input : input string ($1), valid output options ($2)
++# Output: the validated input
++# Note  : the validation list must be an array
++LdapUserInput () {
++declare -a optionAry=("${!2}")
++while true; do
++    read -p "$1" _output
++    # convert to lower case
++    _output2=${_output,,}
++    # check if output is a valid option
++    if [[ "${optionAry[@]}" =~ "$_output2" ]]; then
++	break
++    else
++       echo "Invalid input \"$_output\". Allowed options: ${optionAry[@]}" >&2
++   fi
++done
++   echo "$_output2"
++}
 +
 +# Delete an ldap user if it exists
 +# and exit with error
@@ -74,30 +101,8 @@
 +# Input : username ($1), shell to set ($2)
 +# Output : none
 +LdapAddLoginShell () {
-+  if [ -z "$2" ]; then
-+    # Ask the user for the login shell
-+    echo "Select Login Shell option # [2]: 
-+1) Bash
-+2) Lshell"
-+    read opn
-+    case $opn in
-+      1) _SHELL="/bin/sh";;
-+      2) _SHELL="$_DEFAULTLSHELL";;
-+      *)
-+	 [ ! -z "$opn" ] && echo "Invalid option. Selecting Lshell"
-+         _SHELL="$_DEFAULTLSHELL"
-+	 ;;
-+    esac
-+  else
-+    shellopn=${$2,,}
-+    case $shellopn in
-+      "bash") _SHELL="/bin/sh";;
-+      "lshell") _SHELL="$_DEFAULTLSHELL";;
-+      *)
-+         echo "Invalid option($2). Selecting Lshell"; _SHELL="$_DEFAULTLSHELL"
-+	 ;;
-+    esac
-+  fi
++  # Support bash only now.
++  _SHELL="$_BASHSHELL"
 +  # Replace the login shell
 +  ldapmodifyuser $1 replace loginShell $_SHELL &> /dev/null
 +  [ $? -eq 0 ] || LdapRollback $1 "Critical setup error: cannot set login shell"
@@ -148,14 +153,13 @@
 +  echo "Updating password expiry to $_newWarning days"
 +}
 +
-+
 +# Since this setup script is meant to be a
 +# wrapper on top of existing ldap scripts,
 +# it share invoke those... we could have achieved
 +# loose coupling by not relying on helpers but
 +# at the expense of massively redundant code
 +# duplication.
-+declare -a helper_scripts=("ldapadduser" "ldapaddsudo" "ldapmodifyuser" "ldapaddusertogroup" "$_DEFAULTLSHELL")
++declare -a helper_scripts=("ldapadduser" "ldapaddsudo" "ldapmodifyuser" "ldapaddusertogroup" "$_BASHSHELL")
 +
 +# Do some quick sanity tests to make sure
 +# helper scripts are present
@@ -172,27 +176,23 @@
 +  read _username
 +  LdapAddUser "$_username"
 +
-+  # Replace the login shell. We will prompt the user for this
++  # Replace the login shell. Only bash is supported now.
 +  LdapAddLoginShell "$_username"
 +
-+  # If login shell is NOT the default limited shell then
-+  # prompt for sudo permissions
-+  if [ "$_SHELL" != "$_DEFAULTLSHELL" ]; then
-+    # Should sudo be activated for this user
-+    echo -n "Add $_username to sudoer list? (yes/NO): "
-+    read CONFIRM
-+    CONFIRM=${CONFIRM,,}
++  # Should sudo be activated for this user
++  echo -n "Add $_username to sudoer list? (yes/NO): "
++  read CONFIRM
++  CONFIRM=${CONFIRM,,}
 +
-+    if is_yes $CONFIRM
-+    then
-+      LdapAddSudo "$_username"
-+    fi
++  if is_yes $CONFIRM
++  then
++    LdapAddSudo "$_username"
 +  fi
 +
 +  # Add to secondary user group
-+  echo -n "Add $_username to secondary user group? (yes/NO): "
-+  read CONFIRM
-+  CONFIRM=${CONFIRM,,}
++  shellInput="Add $_username to secondary user group? (yes/NO): "
++  options=( "yes", "no" )
++  CONFIRM=`LdapUserInput "$shellInput" options[@]`
 +  if is_yes $CONFIRM
 +  then
 +    echo -n "Secondary group to add user to? [$_DEFAULTGRP2]: "
@@ -225,10 +225,6 @@
 +	;;
 +	--sudo)      # optional
 +	_sudo="yes"
-+	;;
-+	--shell)     # optional
-+        _loginshell="$2"
-+	shift
 +	;;
 +  	--passmax) # optional
 +	_shadowMax="$2"
@@ -270,9 +266,11 @@
 +  LdapUpdateShadowMax $_username $_shadowMax
 +  LdapUpdateShadowWarning $_username $_shadowWarning
 +fi
+diff --git a/Makefile b/Makefile
+index f81c272..6e5b193 100644
 --- a/Makefile
 +++ b/Makefile
-@@ -41,12 +41,13 @@ SBINFILES =	ldapdeletemachine ldapmodify
+@@ -41,12 +41,13 @@ SBINFILES =	ldapdeletemachine ldapmodifygroup ldapsetpasswd lsldap ldapadduser l
  			ldapdeleteuser ldapsetprimarygroup ldapfinger ldapid ldapgid ldapmodifymachine \
  			ldaprenamegroup ldapaddgroup ldapaddusertogroup ldapdeleteuserfromgroup \
  			ldapinit ldapmodifyuser ldaprenamemachine ldapaddmachine ldapdeletegroup \
@@ -288,9 +286,12 @@
  MAN5FILES = ldapscripts.5
  TMPLFILES = ldapaddgroup.template.sample ldapaddmachine.template.sample \
  			ldapadduser.template.sample
+diff --git a/man/man1/ldapusersetup.1 b/man/man1/ldapusersetup.1
+new file mode 100644
+index 0000000..9b3129b
 --- /dev/null
 +++ b/man/man1/ldapusersetup.1
-@@ -0,0 +1,61 @@
+@@ -0,0 +1,60 @@
 +.\" Copyright (c) 2015 Wind River Systems, Inc.
 +.\"
 +.\" This program is free software; you can redistribute it and/or
@@ -337,7 +338,6 @@
 +The name or uid of the user to modify.
 +The following fields are available as long format options:
 +--sudo                  : whether to add this user to sudoer list
-+--shell <bash | lshell> : which login shell to use (default is lshell)
 +--secondgroup <grp>     : the secondary group to add this user to
 +--passmax     <value>   : the shadowMax value for this user
 +--passwarning <value>   : the shadowWarning value for this user"
