Fix sourcing openrc in collect
The openrc file is being sourced in a short lived
shell rather than in the shell of the sourcing code.

As a result the environment created by the 'source'
does not persist and the inventory request fails
which prevents collect from learning/validating
remote host names.

This update corrects that and makes the code block
involved in learning openrc variables a function
call rather than inline whenever collect_utils
is sourced.

Test Plan:

PASS: Verify collect all with no openrc already sourced
PASS: Verify collect select hosts (same no pre-openrc)
PASS: Verify collect self controller (same no pre-openrc)
PASS: Verify collect of self on compute

Change-Id: I41a097d9d751351f178a1366eb76dfb526c57b19
Closes-Bug: 1837412
Signed-off-by: Eric MacDonald <eric.macdonald@windriver.com>

diff --git a/tools/collector/scripts/collect_utils b/tools/collector/scripts/collect_utils
--- a/tools/collector/scripts/collect_utils
+++ b/tools/collector/scripts/collect_utils
@@ -55,34 +55,37 @@ MIN_PERCENT_SPACE_REQUIRED=75
 COLLECT_LOG=/var/log/collect.log
 COLLECT_ERROR_LOG=/tmp/collect_error.log
 
+function source_openrc_if_needed
+{
+    # get the node and subfunction types
+    nodetype=""
+    subfunction=""
+    PLATFORM_CONF=/etc/platform/platform.conf
+    if [ -e ${PLATFORM_CONF} ] ; then
+        source ${PLATFORM_CONF}
+    fi
 
-# get the node and subfunction types
-nodetype=""
-subfunction=""
-PLATFORM_CONF=/etc/platform/platform.conf
-if [ -e ${PLATFORM_CONF} ] ; then
-    source ${PLATFORM_CONF}
-fi
+    if [ "${nodetype}" != "controller" -a "${nodetype}" != "worker" -a "${nodetype}" != "storage" ] ; then
+        logger -t ${COLLECT_TAG} "could not identify nodetype ($nodetype)"
+        exit $FAIL_NODETYPE
+    fi
 
-if [ "${nodetype}" != "controller" -a "${nodetype}" != "worker" -a "${nodetype}" != "storage" ] ; then
-    logger -t ${COLLECT_TAG} "could not identify nodetype ($nodetype)"
-    exit $FAIL_NODETYPE
-fi
+    NODETYPE=$nodetype
+    SUBFUNCTION=$subfunction
 
-NODETYPE=$nodetype
-SUBFUNCTION=$subfunction
-
-ACTIVE=false
-if [ "$NODETYPE" == "controller" ] ; then
-    # get local host activity state
-    OPENRC="/etc/platform/openrc"
-    if [ -e "${OPENRC}" ] ; then
-        rc=`source ${OPENRC}`
-        if [ "$rc" == "" ] ; then
-            ACTIVE=true
+    ACTIVE=false
+    if [ "$NODETYPE" == "controller" ] ; then
+        # get local host activity state
+        OPENRC="/etc/platform/openrc"
+        if [ -e "${OPENRC}" ] ; then
+            OS_USERNAME=""
+            source ${OPENRC}
+            if [ "${OS_USERNAME}" != "" ] ; then
+                ACTIVE=true
+            fi
         fi
     fi
-fi
+}
 
 
 # Setup an expect command completion file.
