Adds support for 3 monitors on AIO-DX
Adding two fixed Ceph monitors for controllers when deploying an
AIO-DX to improve HA.

Includes:
 - Creates a new shell script to manage the fixed monitors
 - Creates a new patch to include the mon_data parameter in
   the mon.pp puppet manifest.
 - Creates the ceph-storage-network script that is used by the
   storage-networking SM service to stop Ceph services in case
   of a network outage.
 - Alters the script used by the ceph-mds pmon file to
   ceph-init-wrapper.
 - Adjusts the ceph-init-wrapper to accept commands from pmon service.
 - Adjusts the ceph-init-wrapper to accept the forcestop command.
 - Stopping Ceph services using ceph-init-wrapper, it is checked
   if the pid exists before trying.
 - Stopping ceph-mon service using ceph-init-wrapper,
   the ceph-mds is stopped right before to force a re-peering.
 - Starting ceph-mon service using ceph-init-wrapper,
   the ceph-mds is stopped right before to force a re-peering.
 - Starting ceph-mds, it is checked if the ceph-mon is operational.
 - The forcestop command uses a TERM signal first before
   attempting a KILL signal after 5 seconds.

Test Plan:
  PASS: Fresh install AIO-DX and check 3 Ceph monitors are running.
  PASS: Fresh install all other setups and check if Ceph is working as
expected.
  PASS: Reboots the standby controller and check if Ceph is still
running.
  PASS: Reboots the active controller. Ceph will stop responding, but
it will recover after both controllers are running.
  PASS: Verify Ceph is working after a DOR test with PODs writting
to the cephfs and rbd pools.
  PASS: Verify Ceph is resilient to switch reboots

Story: 2011122
Task: 50129

Change-Id: I18d7ab9da3303265da34bc13c8be4baa23c2a7be
Signed-off-by: Hediberto C Silva <hediberto.cavalcantedasilva@windriver.com>
Signed-off-by: Felipe Sanches Zanoni <Felipe.SanchesZanoni@windriver.com>

diff --git a/ceph/ceph/debian/deb_folder/ceph-base.ceph.init b/ceph/ceph/debian/deb_folder/ceph-base.ceph.init
--- a/ceph/ceph/debian/deb_folder/ceph-base.ceph.init
+++ b/ceph/ceph/debian/deb_folder/ceph-base.ceph.init
@@ -623,7 +623,7 @@ stop_daemon() {
 	        if [ \$timeout -lt 0 ]; then
 	            break
 	        fi
-	        timeout-=1
+	        timeout=\$((timeout-1))
 	    fi
 	    cmd=\"kill $signal \$pid\"
 	    printf \"\$cmd...\"
@@ -769,7 +769,7 @@ fi
 # When this is a AIO-DX pmon is monitoring ceph-mds process.
 # If ceph-mon is not running, ceph-mds will hang when starting.
 # Check if we are trying to bring up ceph-mds and ceph-mon is not ready yet
-if [ "${system_type}" == "All-in-one" ] && [ "${system_mode}" == "duplex" ]; then
+if [ "${system_type}" == "All-in-one" ] && [ "${system_mode}" != "simplex" ]; then
     if [ "${command}" = "start" -o "${command}" = "onestart" ]; then
         what_out=
         what_mds=
@@ -873,6 +873,12 @@ for name in $what; do
     # conf file
     cmd="$cmd -c $conf"
 
+    # StarlingX:
+    # If this is AIO-DX, check if service is the fixed Ceph monitor and set the parameter --mon-data
+    if [ "${system_type}" == "All-in-one" ] && [ "${system_mode}" != "simplex" ] && [ "$type" == "mon" ] && [ "$id" == ${HOSTNAME} ]; then
+        cmd="$cmd --mon-data /var/lib/ceph/data/ceph-${HOSTNAME}"
+    fi
+
     if echo $name | grep -q ^osd; then
 	get_conf osd_data "/var/lib/ceph/osd/$cluster-$id" "osd data"
 	get_conf fs_path "$osd_data" "fs path"  # mount point defaults so osd data
@@ -928,13 +934,15 @@ for name in $what; do
 
 	    [ -n "$TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES" ] && tcmalloc="TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=$TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES"
 
-		# StarlingX: start processes in scope under slice system-ceph.slice
-		# so that ceph processes do not start under this script's callers cgroup
-		if [ "$type" = "osd" ]; then
-			cmd="systemd-run --scope --unit=ceph-${type}-${id} --slice=system-ceph $cmd"
-		else
-			cmd="systemd-run --scope --unit=ceph-${type} --slice=system-ceph $cmd"
-		fi
+	    # StarlingX: start processes in scope under slice system-ceph.slice
+	    # so that ceph processes do not start under this script's callers cgroup
+	    if [ "$type" = "osd" ]; then
+	        cmd="systemd-run --scope --unit=ceph-${type}-${id} --slice=system-ceph $cmd"
+	    elif [ "${system_type}" == "All-in-one" ] && [ "${system_mode}" != "simplex" ] && [ "$type" == "mon" ] && [ "$id" == ${HOSTNAME} ]; then
+	        cmd="systemd-run --scope --unit=ceph-${type}-${id} --slice=system-ceph $cmd"
+	    else
+	        cmd="systemd-run --scope --unit=ceph-${type} --slice=system-ceph $cmd"
+	    fi
 
 	    # StarlingX: not running as ceph user/group
 	    cmd="$files $tcmalloc $wrap $cmd --cluster $cluster $runmode"
@@ -988,9 +996,21 @@ for name in $what; do
 		fi
 	    fi
 
+	    echo Starting Ceph $name on $host...
+
+	    if [ $type = "mds" ]; then
+	        echo "Waiting for ceph-mon to respond before starting ceph-mds..."
+		execute_ceph_cmd CMD_OUTPUT $name "ceph fsid"
+	        if [ $? -ne 0 ]; then
+	            log $name "INFO" "Cannot start $name process. Ceph-mon is not working..."
+	            echo "Cannot start ceph-mds. Ceph-mon is not working..."
+	            EXIT_STATUS=$errcode
+		    continue
+	        fi
+	    fi
+
 	    save_proc_startup_ok $name
 
-	    echo Starting Ceph $name on $host...
 	    if [ ! -d $run_dir ]; then
 		# assume /var/run exists
 		install -d -m0770 -o ceph -g ceph /var/run/ceph
@@ -1067,10 +1087,10 @@ EOF
 		# first try to gracefully close process, this should be fast if
 		# its threads still respond to the TERM signal
 		log $name "DEBUG" ">>> Sending term signal"
-		stop_daemon $name ceph-$type $pid_file TERM "" 5
+		stop_daemon $name ceph-$type $pid_file -SIGTERM "" 5
 		log $name "DEBUG" ">>> Sending kill signal"
 		# then just kill it
-		stop_daemon $name ceph-$type $pid_file KILL
+		stop_daemon $name ceph-$type $pid_file -SIGKILL
 	    fi
 
 	    [ -n "$pidfile" ] && rm -f $pidfile
@@ -1182,7 +1202,17 @@ EOF
 	    get_conf pre_forcestop "" "pre forcestop command"
 	    get_conf post_forcestop "" "post forcestop command"
 	    [ -n "$pre_forcestop" ] && do_cmd "$pre_forcestop"
-	    stop_daemon $name ceph-$type $pid_file -9
+
+	    # first try to gracefully close process, this should be fast if
+	    # its threads still respond to the TERM signal
+	    wlog $name "DEBUG" ">>> Sending term signal"
+	    stop_daemon $name ceph-$type $pid_file -SIGTERM "" 5
+	    wlog $name "DEBUG" ">>> Sending kill signal"
+	    # then just kill it
+	    stop_daemon $name ceph-$type $pid_file -SIGKILL
+
+	    [ -n "$pidfile" ] && rm -f $pidfile
+	    [ -n "$asok" ] && rm -f $asok
 	    [ -n "$post_forcestop" ] && do_cmd "$post_forcestop"
 	    [ -n "$lockfile" ] && [ "$?" -eq 0 ] && rm -f $lockfile
 	    ;;
