Update ifupdown-extra patches for trixie
ifupdown-extra Patches updated with latest master branch
fix and with upstream changes. Upversion ifupdown-extra.

Test Plan:
PASS  master trixie build

Story: 2011360
Task: 53556

Change-Id: If18125d3dbf300e2c88a0ee29407029eedd70386
Signed-off-by: Abhinav Ayyapasetti <ayyapasetti.abhinav@windriver.com>

diff --git a/networking/ifupdown-extra/debian/trixie/deb_patches/0006-Only-generate-lack-of-address-warning-if-method-isn-.patch b/networking/ifupdown-extra/debian/trixie/deb_patches/0006-Only-generate-lack-of-address-warning-if-method-isn-.patch
--- a/networking/ifupdown-extra/debian/trixie/deb_patches/0006-Only-generate-lack-of-address-warning-if-method-isn-.patch
+++ b/networking/ifupdown-extra/debian/trixie/deb_patches/0006-Only-generate-lack-of-address-warning-if-method-isn-.patch
@@ -1,10 +1,7 @@
-From da5950d5578aaed4719624400b59402fc335cd7a Mon Sep 17 00:00:00 2001
-From: =?UTF-8?q?Javier=20Fernandez-Sanguino=20Pe=C3=B1a?= <jfs@debian.org>
-Date: Tue, 1 Oct 2024 09:10:11 -0300
+From 6c385528bb28e61b9e83b05315d8b076e0db8a87 Mon Sep 17 00:00:00 2001
+From: Andre Kantek <andrefernandozanella.kantek@windriver.com>
+Date: Tue, 9 Sep 2025 09:19:54 -0300
 Subject: [PATCH] Only generate lack of address warning if method isn't manual
-MIME-Version: 1.0
-Content-Type: text/plain; charset=UTF-8
-Content-Transfer-Encoding: 8bit
 
 The script check-duplicate-ip is generating warning message about
 lack of address config in the interface even if the method is manual.
@@ -12,16 +9,27 @@ The manual method does not provide address to be tested.
 
 This change adds this logic to decide if generates a warning message.
 
+
 Signed-off-by: Andre Kantek <andrefernandozanella.kantek@windriver.com>
 ---
- if-up-scripts/check-duplicate-ip | 4 +++-
- 1 file changed, 3 insertions(+), 1 deletion(-)
+ if-up-scripts/check-duplicate-ip  | 6 ++++--
+ if-up-scripts/check-network-cable | 2 +-
+ 2 files changed, 5 insertions(+), 3 deletions(-)
 
 diff --git a/if-up-scripts/check-duplicate-ip b/if-up-scripts/check-duplicate-ip
-index ec9ff65..b51fa11 100755
+index c9641fe..a3747ba 100755
 --- a/if-up-scripts/check-duplicate-ip
 +++ b/if-up-scripts/check-duplicate-ip
-@@ -127,7 +127,9 @@ esac
+@@ -111,7 +111,7 @@ find_ip() {
+ }
+ 
+ if [ -z "$IFACE" ] ; then
+-    echo "ERROR: Do not know what interface to check. IFACE environment variable is not defined!" >&2
++    $OUT_ERR "Do not know what interface to check. IFACE environment variable is not defined!"
+     exit 0
+ fi
+ 
+@@ -128,7 +128,9 @@ esac
  [ -z "$IF_ADDRESS" ] && find_ip
  # Still no IP? Bail out
  if [ -z "$IF_ADDRESS" ] ; then
@@ -32,6 +40,19 @@ index ec9ff65..b51fa11 100755
      exit 0
  fi
  
+diff --git a/if-up-scripts/check-network-cable b/if-up-scripts/check-network-cable
+index 6b997e8..ce15e80 100755
+--- a/if-up-scripts/check-network-cable
++++ b/if-up-scripts/check-network-cable
+@@ -144,7 +144,7 @@ check_ethernet_status() {
+ 		check_status_sysfs || status=$?
+ 	fi
+ 	[ $status -eq 0 ] ||
+-		$OUTPUT "WARNING: Initialising interface $IFACE which does" \
++		$OUT_WARN "Initialising interface $IFACE which does" \
+ 			"not have a link"
+ 	return $status
+ }
 -- 
 2.34.1
 
